name: arduino_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build on Arduino CLI
      run: bash ci/build-arduino.sh
    - name: upload binareies
      uses: actions/upload-artifact@v2
      with:
        name: build_binary
        path: build/
